### ISSUE TITLE
Change name of workshop in description

### ISSUE THREAD

**Issue by amynic** [GlobalAICommunity/Workshop-VisualInterfaceAutoMLWine#2]
Visual interface is no longer used as a term could we say Automated ML UI instead?

**Comment by hnky** [comment]
Isn't it called Azure Machine Learning Designer now?

**Comment by hnky** [comment]
Sorry lower d: Azure Machine Learning designer

**Comment by amynic** [comment]
Azure Machine Learning designer is the old visual interface with connected modules click and drag etc: https://docs.microsoft.com/en-us/azure/machine-learning/service/tutorial-designer-automobile-price-train-score 

not related to automated ml
